### ISSUE TITLE
How did you start your own company?

### ISSUE THREAD

**Issue by ghost** [lijiarui/ama#2]
I am writing a lot in python, scripts for my work and work with SQL as well. Do you think those skills are adequate to help me start an app like you? What would you suggest, any reading that helped you?

Thank you!
Lefkios

**Comment by lijiarui** [comment]
The skills are always not adequate to start an app, what you need is the ability to keep study and integration all help and resources from others.

For my company or my product, all is not my personal thing, it is a team.

But if you just want to start an app for your interest, just keep study and follow your heart.

**Comment by ghost** [comment]
Thank you for your reply! I appreciate it!
