### ISSUE TITLE
hello world :D

### ISSUE THREAD

**Issue by tech-cow** [lijiarui/ama#3]
Good Taste：Sindre Sorhus的粉丝+1
Blog读后感：佳芮你是个很酷很酷的人，看到了你的坚持不懈，加油呀。

**Comment by lijiarui** [comment]
:) 感谢 同加油呀~  看了你的经历也蛮有意思的~

**Comment by tech-cow** [comment]
看到个资源，感觉应该对你有用！https://github.com/littlecodersh/ItChat

**Comment by lijiarui** [comment]
Thanks! 
See more here: 
* [RelatedProjects](https://github.com/Chatie/wechaty/wiki/RelatedProjects)
* [Puppet](https://github.com/Chatie/wechaty/wiki/Puppet)

Welcome to add more info to our project!
